const KEY='ra_donnerfaust_data_v1';
const initial={
 cases:[{id:'AZ-2026-001',title:'Staat gegen Miller',client:'John Miller',status:'In Bearbeitung',type:'Strafrecht',deadline:'12.09.2026',note:'Vorbereitung der Hauptverhandlung und Prüfung der Beweislage.'},{id:'AZ-2026-002',title:'Mietstreit Becker',client:'Anna Becker',status:'Offen',type:'Zivilrecht',deadline:'18.09.2026',note:'Schriftliche Stellungnahme vorbereiten.'},{id:'AZ-2026-003',title:'Verkehrssache Wagner',client:'Max Wagner',status:'Abgeschlossen',type:'Verkehrsrecht',deadline:'—',note:'Verfahren erfolgreich beendet.'}],
 clients:[{id:1,name:'John Miller',phone:'555-0101',email:'john.miller@example.com',cases:1},{id:2,name:'Anna Becker',phone:'555-0102',email:'anna.becker@example.com',cases:1},{id:3,name:'Max Wagner',phone:'555-0103',email:'max.wagner@example.com',cases:1}],
 appointments:[{date:'12.09.2026',time:'10:00',title:'Hauptverhandlung – Miller',place:'Gerichtssaal 2'},{date:'14.09.2026',time:'16:30',title:'Mandantengespräch – Becker',place:'Kanzlei'},{date:'18.09.2026',time:'09:00',title:'Frist – Mietstreit Becker',place:'Intern'}],
 tasks:[{text:'Miller-Akte vollständig vorbereiten',done:false},{text:'Stellungnahme Becker fertigstellen',done:false},{text:'Abschlussrechnung Wagner erstellen',done:true}],
 messages:[{from:'Kanzlei',text:'Willkommen im internen Kanzleisystem.',time:'Heute 09:15'},{from:'System',text:'Das System wurde erfolgreich bereitgestellt.',time:'Heute 09:16'}],
 announcements:[{title:'Kanzleibetrieb',text:'Alle Akten und Fristen sind zentral im System zu führen.'},{title:'RP-Hinweis',text:'Dieses System dient ausschließlich der Verwaltung innerhalb des Roleplays.'}],
 notes:'', invoices:[{no:'RE-2026-001',client:'John Miller',amount:'2.400 €',status:'Offen'},{no:'RE-2026-002',client:'Anna Becker',amount:'1.200 €',status:'Entwurf'},{no:'RE-2026-003',client:'Max Wagner',amount:'1.850 €',status:'Bezahlt'}], employees:[{name:'Thorson Donnerfaust',role:'Kanzleiinhaber',status:'Online'}]
};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||initial;
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const navItems=[['dashboard','▦','Dashboard'],['cases','⚖','Akten & Fälle'],['clients','👤','Mandanten'],['calendar','▣','Termine / Kalender'],['messages','💬','Nachrichten'],['notifications','🔔','Benachrichtigungen'],['announcements','📢','Ankündigungen'],['documents','📁','Dokumente'],['invoices','€','Gebühren / Rechnungen'],['tasks','☑','Aufgaben'],['notes','📝','Notizen'],['search','⌕','Zentrale Suche'],['employees','👥','Mitarbeiter'],['admin','⚙','Verwaltung']];
let current='dashboard';
function shell(){document.body.innerHTML=`<aside class="sidebar" id="sidebar"><div class="sidebrand"><div class="logo">⚖</div><div><b>Rechtsanwalt Donnerfaust</b><small>Kanzleiverwaltung · RP</small></div></div><nav>${navItems.map(x=>`<button class="nav ${x[0]===current?'active':''}" data-page="${x[0]}"><i>${x[1]}</i>${x[2]}</button>`).join('')}</nav><div class="sidefoot"><span class="online"></span><div><b>Donnerfaust</b><small>Online · Kanzleiinhaber</small></div></div></aside><main class="main"><header class="top"><div><button class="hamb" id="hamb">☰</button><span class="crumb">KANZLEI / RP-SYSTEM</span><h2 id="title">Dashboard</h2></div><div class="topright"><span class="online"></span><b>Thorson Donnerfaust</b><span class="avatar">TD</span></div></header><section class="content" id="content"></section></main>`; document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{current=b.dataset.page;render()});document.getElementById('hamb').onclick=()=>document.getElementById('sidebar').classList.toggle('open');}
function pageTitle(){return navItems.find(x=>x[0]===current)?.[2]||'Dashboard'}
function btn(text,cls='dark',action='') {return `<button class="btn ${cls}" ${action?`data-action="${action}"`:''}>${text}</button>`}
function dashboard(){return `<div class="intro"><div><div class="eyebrow">KANZLEIÜBERSICHT</div><h1>Guten Tag, Rechtsanwalt Donnerfaust.</h1><p>Alle wichtigen Vorgänge deiner Kanzlei auf einen Blick.</p></div>${btn('+ Neue Akte','dark','newcase')}</div><div class="stats"><div class="stat"><span>⚖</span><div><small>OFFENE AKTEN</small><b>${data.cases.filter(x=>x.status!=='Abgeschlossen').length}</b></div></div><div class="stat"><span>👤</span><div><small>MANDANTEN</small><b>${data.clients.length}</b></div></div><div class="stat"><span>📅</span><div><small>TERMINE</small><b>${data.appointments.length}</b></div></div><div class="stat"><span>€</span><div><small>OFFENE RECHNUNGEN</small><b>${data.invoices.filter(x=>x.status!=='Bezahlt').length}</b></div></div></div><div class="grid2"><div class="panel"><div class="panelhead"><b>Nächste Termine</b>${btn('Alle anzeigen','outline','calendar')}</div>${data.appointments.slice(0,4).map(a=>`<div class="timeline"><b>${esc(a.time)}</b><div><strong>${esc(a.title)}</strong><small>${esc(a.date)} · ${esc(a.place)}</small></div></div>`).join('')}</div><div class="panel"><div class="panelhead"><b>Aufgaben</b>${btn('Aufgaben','outline','tasks')}</div>${data.tasks.slice(0,4).map((t,i)=>`<div class="task ${t.done?'done':''}"><input type="checkbox" data-task="${i}" ${t.done?'checked':''}><span><b>${esc(t.text)}</b><small>${t.done?'Erledigt':'Offen'}</small></span></div>`).join('')}</div></div><div class="grid2"><div class="panel"><div class="panelhead"><b>Aktuelle Akten</b>${btn('Akten öffnen','outline','cases')}</div>${data.cases.map(c=>`<div class="listrow"><b>${esc(c.id)} · ${esc(c.title)}</b><small>${esc(c.client)} · ${esc(c.type)} · <span class="badge">${esc(c.status)}</span></small></div>`).join('')}</div><div class="panel"><div class="panelhead"><b>Aktivität</b></div><div class="activityline"><b>System bereit</b><small>Die Kanzleiverwaltung ist aktiv.</small></div><div class="activityline"><b>${data.cases.length} Akten</b><small>im zentralen Aktenbestand</small></div><div class="activityline"><b>${data.clients.length} Mandanten</b><small>im Mandantenverzeichnis</small></div></div></div>`}
function cases(){return `<div class="intro"><div><div class="eyebrow">AKTENVERWALTUNG</div><h1>Akten & Fälle</h1><p>Aktenzeichen, Mandanten, Fristen und Bearbeitungsstand.</p></div>${btn('+ Neue Akte','dark','newcase')}</div><div class="panel"><input class="fullinput" id="casefilter" placeholder="Akten durchsuchen …"><div class="tablewrap"><table><thead><tr><th>AKTENZEICHEN</th><th>FALL</th><th>MANDANT</th><th>RECHTSGEBIET</th><th>FRIST</th><th>STATUS</th><th></th></tr></thead><tbody id="casetable">${caseRows(data.cases)}</tbody></table></div></div>`}
function caseRows(arr){return arr.map((c,i)=>`<tr><td><b>${esc(c.id)}</b></td><td>${esc(c.title)}<small>${esc(c.note)}</small></td><td>${esc(c.client)}</td><td>${esc(c.type)}</td><td>${esc(c.deadline)}</td><td><span class="badge">${esc(c.status)}</span></td><td><button class="mini" data-case="${i}">Öffnen</button></td></tr>`).join('')||`<tr><td colspan="7">Keine Akten vorhanden.</td></tr>`}
function clients(){return `<div class="intro"><div><div class="eyebrow">MANDANTENVERWALTUNG</div><h1>Mandanten</h1><p>Kontakte und zugehörige Verfahren zentral verwalten.</p></div>${btn('+ Neuer Mandant','dark','newclient')}</div><div class="cards">${data.clients.map((c,i)=>`<div class="client"><div class="avatar">${esc(c.name.split(' ').map(x=>x[0]).join('').slice(0,2))}</div><div><b>${esc(c.name)}</b><small>${esc(c.email)}</small><small>${esc(c.phone)}</small><small>${c.cases} Akte(n)</small></div><button class="mini" data-client="${i}">Öffnen</button></div>`).join('')}</div>`}
function calendar(){return `<div class="intro"><div><div class="eyebrow">TERMINE</div><h1>Kalender</h1><p>Gerichtstermine, Mandantengespräche und Fristen.</p></div>${btn('+ Termin','dark','newappointment')}</div><div class="calendarlist">${data.appointments.map(a=>`<div class="calendaritem"><div class="caldate"><small>${esc(a.date.slice(3))}</small><b>${esc(a.date.slice(0,2))}</b></div><div><b>${esc(a.time)} · ${esc(a.title)}</b><small>${esc(a.place)}</small></div></div>`).join('')}</div>`}
function messages(){return `<div class="intro"><div><div class="eyebrow">INTERNE KOMMUNIKATION</div><h1>Nachrichten</h1><p>Interner Kanzlei-Chat.</p></div></div><div class="chat"><div class="chathead"><b>Kanzlei intern</b><span class="badge">🟢 Online</span></div><div class="messages">${data.messages.map(m=>`<div class="message"><div class="avatar">${esc(m.from.slice(0,2).toUpperCase())}</div><div><b>${esc(m.from)}</b><small>${esc(m.time)}</small><p>${esc(m.text)}</p></div></div>`).join('')}<form id="msgform" style="display:flex;gap:8px;padding-top:15px"><input class="fullinput" id="msginput" style="margin:0" placeholder="Nachricht schreiben …"><button class="btn dark">Senden</button></form></div></div>`}
function notifications(){return `<div class="intro"><div><div class="eyebrow">BENACHRICHTIGUNGEN</div><h1>Benachrichtigungen</h1><p>Fristen und Systemmeldungen.</p></div></div><div class="panel">${data.cases.filter(c=>c.status!=='Abgeschlossen').map(c=>`<div class="notification"><span>🔔</span><div><b>Frist: ${esc(c.id)}</b><small>${esc(c.deadline)} · ${esc(c.title)}</small></div></div>`).join('')||'<p class="muted">Keine offenen Benachrichtigungen.</p>'}</div>`}
function announcements(){return `<div class="intro"><div><div class="eyebrow">KANZLEI-INTERN</div><h1>Ankündigungen</h1><p>Interne Bekanntmachungen.</p></div>${btn('+ Ankündigung','dark','newannouncement')}</div><div class="announce">${data.announcements.map(a=>`<div class="panel"><div class="eyebrow">KANZLEI</div><h3>${esc(a.title)}</h3><p>${esc(a.text)}</p></div>`).join('')}</div>`}
function documents(){return `<div class="intro"><div><div class="eyebrow">DOKUMENTE</div><h1>Dokumente</h1><p>Zentrale Dokumentenablage der Kanzlei.</p></div></div><div class="panel"><div class="listrow"><b>📄 Aktenvorlagen</b><small>Vorlagen für neue Verfahren und Mandanten</small></div><div class="listrow"><b>📄 Schriftsätze</b><small>Interne Schriftsatzvorlagen</small></div><div class="listrow"><b>📄 Vollmachten</b><small>RP-Vorlagen für Mandate</small></div><p class="muted">Hinweis: GitHub Pages speichert keine privaten Dateien sicher. Diese Oberfläche ist für dein RP gedacht.</p></div>`}
function invoices(){return `<div class="intro"><div><div class="eyebrow">FINANZEN</div><h1>Gebühren & Rechnungen</h1><p>Rechnungen und Gebührenübersicht.</p></div>${btn('+ Rechnung','dark','newinvoice')}</div><div class="panel"><div class="tablewrap"><table><thead><tr><th>RECHNUNG</th><th>MANDANT</th><th>BETRAG</th><th>STATUS</th></tr></thead><tbody>${data.invoices.map(x=>`<tr><td><b>${esc(x.no)}</b></td><td>${esc(x.client)}</td><td>${esc(x.amount)}</td><td><span class="badge">${esc(x.status)}</span></td></tr>`).join('')}</tbody></table></div></div>`}
function tasks(){return `<div class="intro"><div><div class="eyebrow">ARBEITSPLAN</div><h1>Aufgaben</h1><p>Persönliche und kanzleiinterne Aufgaben.</p></div>${btn('+ Aufgabe','dark','newtask')}</div><div class="panel">${data.tasks.map((t,i)=>`<div class="task ${t.done?'done':''}"><input type="checkbox" data-task="${i}" ${t.done?'checked':''}><span><b>${esc(t.text)}</b><small>${t.done?'Erledigt':'Offen'}</small></span></div>`).join('')}</div>`}
function notes(){return `<div class="intro"><div><div class="eyebrow">PERSÖNLICH</div><h1>Notizen</h1><p>Interne Arbeitsnotizen.</p></div>${btn('Speichern','dark','savenotes')}</div><div class="panel"><textarea id="notes" class="fullinput" style="min-height:420px;resize:vertical">${esc(data.notes)}</textarea></div>`}
function search(){return `<div class="intro"><div><div class="eyebrow">ZENTRAL</div><h1>Suche</h1><p>Durchsuche Akten, Mandanten und Rechnungen.</p></div></div><div class="panel"><input class="fullinput" id="globalsearch" placeholder="Suchbegriff …"><div id="results"></div></div>`}
function employees(){return `<div class="intro"><div><div class="eyebrow">PERSONAL</div><h1>Mitarbeiter</h1><p>Interne Benutzer und Rollen.</p></div>${btn('+ Mitarbeiter','dark','newemployee')}</div><div class="panel">${data.employees.map(e=>`<div class="client" style="border:0;border-top:1px solid #edf0f3;border-radius:0"><div class="avatar">TD</div><div><b>${esc(e.name)}</b><small>${esc(e.role)}</small><small>🟢 ${esc(e.status)}</small></div></div>`).join('')}</div>`}
function admin(){return `<div class="intro"><div><div class="eyebrow">VERWALTUNG</div><h1>Verwaltung</h1><p>Systemeinstellungen und Kanzleikonfiguration.</p></div></div><div class="casegrid"><div class="panel"><h3>Benutzer & Rechte</h3><div class="field"><small>AKTIVER BENUTZER</small><b>Thorson Donnerfaust</b></div><div class="field"><small>ROLLE</small><b>Kanzleiinhaber / Administrator</b></div><div class="field"><small>BERECHTIGUNGEN</small><b>Vollzugriff</b></div></div><div class="panel"><h3>System</h3><div class="field"><small>DATENSPEICHER</small><b>Lokaler Browser-Speicher</b></div><div class="field"><small>VERSION</small><b>1.0 · RP Kanzleisystem</b></div><div class="field"><small>STATUS</small><b>🟢 Betriebsbereit</b></div>${btn('Daten zurücksetzen','danger','reset')}</div></div>`}
function render(){shell();document.getElementById('title').textContent=pageTitle();const views={dashboard,cases,clients,calendar,messages,notifications,announcements,documents,invoices,tasks,notes,search,employees,admin};document.getElementById('content').innerHTML=views[current]();bind();}
function modal(title,fields,submit){document.body.insertAdjacentHTML('beforeend',`<div class="modalback" id="modal"><div class="modal"><div class="modalhead"><b>${title}</b><button id="closemodal">×</button></div><form id="modalform">${fields.map(f=>`<label>${f.label}<input name="${f.name}" ${f.required===false?'':'required'} placeholder="${f.placeholder||''}"></label>`).join('')}<button class="btn dark">${submit}</button></form></div></div>`);document.getElementById('closemodal').onclick=()=>document.getElementById('modal').remove();document.getElementById('modalform').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));document.getElementById('modal').remove();return handleModal(title,o)} }
function handleModal(title,o){if(title.includes('Akte'))data.cases.unshift({id:'AZ-'+new Date().getFullYear()+'-'+String(data.cases.length+1).padStart(3,'0'),title:o.title,client:o.client,status:'Offen',type:o.type||'Allgemein',deadline:o.deadline||'—',note:o.note||''});else if(title.includes('Mandant'))data.clients.push({id:Date.now(),name:o.name,phone:o.phone||'—',email:o.email||'—',cases:0});else if(title.includes('Termin'))data.appointments.push({date:o.date,time:o.time,title:o.title,place:o.place||'Kanzlei'});else if(title.includes('Aufgabe'))data.tasks.push({text:o.text,done:false});else if(title.includes('Ankündigung'))data.announcements.unshift({title:o.title,text:o.text});else if(title.includes('Rechnung'))data.invoices.unshift({no:'RE-'+new Date().getFullYear()+'-'+String(data.invoices.length+1).padStart(3,'0'),client:o.client,amount:o.amount,status:'Entwurf'});else if(title.includes('Mitarbeiter'))data.employees.push({name:o.name,role:o.role||'Mitarbeiter',status:'Online'});save();render();}
function bind(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='newcase')modal('Neue Akte',[{label:'Fallbezeichnung',name:'title'},{label:'Mandant',name:'client'},{label:'Rechtsgebiet',name:'type'},{label:'Frist',name:'deadline',required:false},{label:'Notiz',name:'note',required:false}],'Akte anlegen');if(a==='newclient')modal('Neuer Mandant',[{label:'Name',name:'name'},{label:'Telefon',name:'phone',required:false},{label:'E-Mail',name:'email',required:false}],'Mandant anlegen');if(a==='newappointment')modal('Neuer Termin',[{label:'Datum',name:'date'},{label:'Uhrzeit',name:'time'},{label:'Termin',name:'title'},{label:'Ort',name:'place',required:false}],'Termin anlegen');if(a==='newtask')modal('Neue Aufgabe',[{label:'Aufgabe',name:'text'}],'Aufgabe anlegen');if(a==='newannouncement')modal('Neue Ankündigung',[{label:'Titel',name:'title'},{label:'Text',name:'text'}],'Veröffentlichen');if(a==='newinvoice')modal('Neue Rechnung',[{label:'Mandant',name:'client'},{label:'Betrag',name:'amount'}],'Rechnung anlegen');if(a==='newemployee')modal('Mitarbeiter anlegen',[{label:'Name',name:'name'},{label:'Rolle',name:'role'}],'Mitarbeiter anlegen');if(a==='tasks')current='tasks',render();if(a==='calendar')current='calendar',render();if(a==='cases')current='cases',render();if(a==='reset'){if(confirm('Alle lokalen RP-Daten zurücksetzen?')){localStorage.removeItem(KEY);location.reload()}}});
document.querySelectorAll('[data-task]').forEach(x=>x.onchange=()=>{data.tasks[+x.dataset.task].done=x.checked;save();render()});
const cf=document.getElementById('casefilter');if(cf)cf.oninput=()=>{const q=cf.value.toLowerCase();document.getElementById('casetable').innerHTML=caseRows(data.cases.filter(c=>Object.values(c).join(' ').toLowerCase().includes(q)));bind()};
const sf=document.getElementById('globalsearch');if(sf)sf.oninput=()=>{const q=sf.value.toLowerCase();let r=[];data.cases.forEach(c=>{if(Object.values(c).join(' ').toLowerCase().includes(q))r.push(`<div class="result"><b>⚖ Akte ${esc(c.id)}</b><small>${esc(c.title)} · ${esc(c.client)}</small></div>`)});data.clients.forEach(c=>{if(Object.values(c).join(' ').toLowerCase().includes(q))r.push(`<div class="result"><b>👤 Mandant</b><small>${esc(c.name)} · ${esc(c.email)}</small></div>`)});data.invoices.forEach(c=>{if(Object.values(c).join(' ').toLowerCase().includes(q))r.push(`<div class="result"><b>€ ${esc(c.no)}</b><small>${esc(c.client)} · ${esc(c.amount)}</small></div>`)});document.getElementById('results').innerHTML=q?(r.join('')||'<p class="muted">Keine Treffer.</p>'):''};
const mf=document.getElementById('msgform');if(mf)mf.onsubmit=e=>{e.preventDefault();const i=document.getElementById('msginput');if(i.value.trim()){data.messages.push({from:'Donnerfaust',text:i.value.trim(),time:'Gerade eben'});save();render()}};
const sn=document.querySelector('[data-action="savenotes"]');if(sn)sn.onclick=()=>{data.notes=document.getElementById('notes').value;save();alert('Notizen gespeichert.')};
}
if(!sessionStorage.getItem('ra_logged_in')){document.body.innerHTML=`<div style="min-height:100vh;display:grid;place-items:center;background:#111827;padding:20px"><div style="width:min(430px,100%);background:white;border-radius:20px;padding:34px;text-align:center;box-shadow:0 25px 80px #0005"><div style="width:64px;height:64px;border-radius:18px;background:#111827;color:white;display:grid;place-items:center;font-size:32px;margin:0 auto 20px">⚖</div><div class="eyebrow">KANZLEISYSTEM · ROLEPLAY</div><h1 style="margin:8px 0 6px">Rechtsanwalt Donnerfaust</h1><p style="color:#727d8e">Persönlicher Mitarbeiterbereich</p><button id="login" class="btn dark" style="width:100%;margin-top:15px">🔐 Kanzleibereich öffnen</button><p style="font-size:11px;color:#8992a1;margin-top:18px">RP-Anwendung · Daten werden lokal im Browser gespeichert.</p></div></div>`;document.getElementById('login').onclick=()=>{sessionStorage.setItem('ra_logged_in','1');render()}}else render();