/* Rechtsanwalt Donnerfaust – Mitarbeitervergütung
   Rollen sind ausschließlich Aufgaben-Zuordnung, KEINE Zugriffsrechte.
   Rollen: Sekretär, Rechtsanwalt, Inhaber
   Sekretär: 500 €/Stunde; Rechtsanwalt/Inhaber: 20 % je zugeordneter bezahlter Rechnung.
*/
(() => {
  const DBKEY="donnerfaust_kanzlei_v1", PAYKEY="donnerfaust_employee_pay_v3";
  const ROLES=["Sekretär","Rechtsanwalt","Inhaber"], HOURLY={"Sekretär":500};
  const read=()=>{try{return JSON.parse(localStorage.getItem(DBKEY)||"{}")}catch{return{}}};
  const write=d=>localStorage.setItem(DBKEY,JSON.stringify(d));
  const load=()=>{try{return JSON.parse(localStorage.getItem(PAYKEY)||"{}")}catch{return{}}};
  const save=p=>localStorage.setItem(PAYKEY,JSON.stringify(p));
  const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
  const eur=n=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(n)||0);
  const day=()=>new Date().toISOString().slice(0,10);
  const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const role=e=>e?.role==="Kanzleiinhaber"||e?.role==="Stellv. Inhaber"?"Inhaber":(e?.role==="Assistent"?"Rechtsanwalt":(ROLES.includes(e?.role)?e.role:"Rechtsanwalt"));
  const paid=i=>String(i?.status||"").trim().toLowerCase()==="bezahlt";
  const assigned=(i,id)=>[i?.employee_id,i?.employeeId,i?.lawyer_id,i?.assigned_employee_id,i?.responsible_employee_id].some(v=>String(v??"")===String(id));
  function normalize(){const d=read(); if(!Array.isArray(d.employees))return; let ch=false; d.employees.forEach(e=>{const r=role(e);if(e.role!==r){e.role=r;ch=true;}});if(ch)write(d)}
  function payRecord(e){const p=load();p[e.id] ||= {hours:{},payout:"weekly",paid:0};p[e.id].hours ||= {};p[e.id].payout ||= "weekly";p[e.id].paid=Number(p[e.id].paid)||0;save(p);return p[e.id]}
  function hoursTotal(p){return Object.values(p.hours||{}).reduce((s,v)=>s+Math.max(0,Number(v)||0),0)}
  function invoice20(e){const d=read(),p=payRecord(e),credited=p.credited||{};return (d.invoices||[]).filter(i=>paid(i)&&assigned(i,e.id)&&!credited[i.id]).reduce((s,i)=>s+(Number(i.amount)||0)*.2,0)}
  function amount(e){const p=payRecord(e);return role(e)==="Sekretär"?hoursTotal(p)*500+Number(p.paid||0):invoice20(e)+Number(p.paid||0)}
  function migrateOldPay(){const old=(()=>{try{return JSON.parse(localStorage.getItem("donnerfaust_employee_pay_v2")||"{}")}catch{return{}}})();const p=load();Object.entries(old).forEach(([id,v])=>{p[id] ||= {hours:{},payout:v.payout||"weekly",paid:0};p[id].hours ||= {};Object.entries(v.entries||{}).forEach(([d,h])=>{if(!p[id].hours[d])p[id].hours[d]=h});p[id].paid=Number(p[id].paid)||0});save(p)}
  function cards(){normalize();migrateOldPay();const d=read(),pall=load();return (d.employees||[]).map(e=>{const r=role(e),p=pall[e.id]||{hours:{},payout:"weekly",paid:0},hrs=hoursTotal(p),sum=amount(e),today=day();return `<div class="panel df-employee-pay" style="margin-top:12px"><div class="panelhead"><div><b>${esc(e.name||"Unbenannt")}</b><small>${esc(r)}</small></div><div style="text-align:right"><b>${eur(sum)}</b><small>Offene Auszahlung</small></div></div>${r==="Sekretär"?`<div style="margin:12px 0;padding:12px;border:1px solid #dfe3ea;border-radius:12px"><label><b>Arbeitszeit heute (${today})</b><input type="number" min="0" max="24" step="0.25" value="${Number(p.hours[today])||0}" data-df-hours="${esc(e.id)}" inputmode="decimal"><small>500,00 € / Stunde · Tagessumme: <b data-df-day="${esc(e.id)}">${eur((Number(p.hours[today])||0)*500)}</b></small></label></div><div><b>Gesamtstunden:</b> ${hrs.toLocaleString("de-DE")} h · <b>Stundenlohn:</b> ${eur(hrs*500)}</div>`:`<div style="padding:12px 0"><b>Vergütung:</b> 20 % der zugeordneten bezahlten Rechnungen</div>`}<div style="margin-top:10px"><b>Gesamtauszahlung: ${eur(sum)}</b></div><div class="df-pay-controls" style="margin-top:12px"><label>Auszahlung <select data-df-mode="${esc(e.id)}"><option value="weekly" ${p.payout==="weekly"?"selected":""}>Wöchentlich</option><option value="daily" ${p.payout==="daily"?"selected":""}>Täglich</option><option value="manual" ${p.payout==="manual"?"selected":""}>Manuell</option></select></label><button class="btn dark" data-df-payout="${esc(e.id)}">✓ Ausgezahlt</button></div></div>`}).join("")}
  function patch(){if(typeof window.employees!=="function")return;if(window.employees.__dfPayroll3)return;const old=window.employees;const fn=function(){const base=old();return base+`<div class="panel" style="margin-top:18px"><div class="panelhead"><div><b>Mitarbeitervergütung</b><small>Rollen haben keine Zugriffsrechte.</small></div></div><p class="muted" style="margin:0">Sekretär: 500 €/Stunde. Rechtsanwalt und Inhaber: 20 % der zugeordneten bezahlten Rechnungen.</p></div>${cards()}`};fn.__dfPayroll3=true;window.employees=fn}
  function setHours(id,val){const d=read(),e=(d.employees||[]).find(x=>String(x.id)===String(id));if(!e||role(e)!=="Sekretär")return;const p=payRecord(e),n=Math.max(0,Math.min(24,Number(String(val).replace(",","."))||0));if(n)p.hours[day()]=n;else delete p.hours[day()];const all=load();all[id]=p;save(all);if(typeof render==="function")render()}
  function payout(id){const d=read(),e=(d.employees||[]).find(x=>String(x.id)===String(id));if(!e)return;const p=payRecord(e),sum=amount(e);if(sum<=0)return alert("Kein auszuzahlender Betrag vorhanden.");d.cashbook ||= [];const bal=d.cashbook.reduce((s,x)=>s+(x.kind==="in"?1:-1)*(Number(x.amount)||0),0);if(bal<sum)return alert(`Kassenbestand zu niedrig: ${eur(bal)} verfügbar, ${eur(sum)} benötigt.`);d.cashbook.push({id:uid(),kind:"out",amount:sum,reason:`Mitarbeiterzahlung: ${e.name} (${role(e)})`,date:new Date().toLocaleString("de-DE"),source:"employee",employee_id:e.id});p.paid=0;p.hours={};if(role(e)!=="Sekretär"){const d2=read();const pp=load();pp[id] ||= p;pp[id].credited ||= {};d2.invoices?.filter(i=>paid(i)&&assigned(i,id)).forEach(i=>pp[id].credited[i.id]=true);save(pp);write(d2)}else{const pp=load();pp[id]=p;save(pp);write(d)}if(typeof render==="function")render()}
  function bind(){normalize();patch();document.addEventListener("input",e=>{const f=e.target.closest("[data-df-hours]");if(!f)return;setHours(f.dataset.dfHours,f.value);const out=document.querySelector(`[data-df-day="${CSS.escape(f.dataset.dfHours)}"]`);if(out)out.textContent=eur((Number(String(f.value).replace(",","."))||0)*500)});document.addEventListener("change",e=>{const f=e.target.closest("[data-df-mode]");if(!f)return;const p=load();p[f.dataset.dfMode] ||= {hours:{},paid:0};p[f.dataset.dfMode].payout=f.value;save(p)});document.addEventListener("click",e=>{const b=e.target.closest("[data-df-payout]");if(!b)return;e.preventDefault();e.stopPropagation();payout(b.dataset.dfPayout)},true);new MutationObserver(patch).observe(document.body,{childList:true,subtree:true})}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
})();