/* Beweise: Ordner mit mehreren Bildern/Videos + ein gemeinsamer externer Link. */
(() => {
  const SUPABASE_URL="https://qsyijgvikxmwmhaiulne.supabase.co";
  const SUPABASE_KEY="sb_publishable_5qeUg0c0T0IyLh8g0cUj6Q_ZJYgZYJ_";
  const BUCKET="evidence", STATE_KEY="donnerfaust_kanzlei_v1", VIEWER="./beweis.html";
  const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
  const read=()=>{try{return JSON.parse(localStorage.getItem(STATE_KEY)||"{}")}catch{return {}}}; const write=x=>localStorage.setItem(STATE_KEY,JSON.stringify(x));
  const client=window.supabase?.createClient?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null; let activeCase="";
  const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  function addNav(){const nav=document.querySelector(".sidebar nav");if(!nav||nav.querySelector('[data-evidence-nav]'))return;const b=document.createElement("button");b.className="nav";b.dataset.evidenceNav="1";b.innerHTML="<i>🔎</i>Beweise";b.onclick=()=>openPanel("");const docs=[...nav.querySelectorAll(".nav")].find(x=>x.dataset.nav==="documents"||x.textContent.includes("Dokumente"));if(docs)docs.insertAdjacentElement("afterend",b);else nav.appendChild(b)}
  function folderUrl(folderId){const u=new URL(VIEWER,location.href);u.searchParams.set("folder",folderId);return u.href}
  function openPanel(caseId=""){activeCase=caseId||"";const db=read(),cases=db.cases||[],folders=(db.evidence_folders||[]).filter(x=>!activeCase||x.case_id===activeCase);const root=document.getElementById("modalroot")||document.body.appendChild(Object.assign(document.createElement("div"),{id:"modalroot"}));root.innerHTML=`<div class="modalback"><div class="modal" style="max-width:900px"><div class="modalhead"><b>Beweisordner</b><button id="evClose" type="button">×</button></div><form id="folderForm"><label>Name des Beweisordners<input name="name" required placeholder="z. B. Beweismittel Akte AZ-2026-001"></label><label>Akte<select name="case_id"><option value="">Allgemeiner Beweisordner</option>${cases.map(c=>`<option value="${esc(c.id)}" ${c.id===activeCase?"selected":""}>${esc(c.file_number)} · ${esc(c.title)}</option>`).join("")}</select></label><button class="btn dark" type="submit">+ Ordner anlegen</button></form><hr>${folders.map(f=>`<div class="panel" style="margin:12px 0"><div class="panelhead"><b>📁 ${esc(f.name)}</b><span>${(f.items||[]).length} Dateien</span></div><div class="actions"><button class="btn outline" type="button" data-add="${f.id}">+ Bilder/Videos hinzufügen</button><button class="btn outline" type="button" data-share="${f.id}">🔗 Gemeinsamen Link kopieren</button></div><div>${(f.items||[]).map(x=>`<div class="listrow"><b>${esc(x.name)}</b><small>${esc(x.type||"")}</small></div>`).join("")||'<p class="muted">Noch keine Dateien.</p>'}</div>`).join("")||'<p class="muted">Noch keine Beweisordner.</p>'}</div></div>`;document.getElementById("evClose").onclick=()=>root.innerHTML="";document.getElementById("folderForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),db=read();db.evidence_folders=db.evidence_folders||[];db.evidence_folders.push({id:id(),name:String(f.get("name")||"").trim(),case_id:String(f.get("case_id")||""),items:[],created_at:new Date().toISOString()});write(db);openPanel(activeCase)};root.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addFile(b.dataset.add));root.querySelectorAll("[data-share]").forEach(b=>b.onclick=()=>{const u=folderUrl(b.dataset.share);navigator.clipboard?.writeText(u).then(()=>alert("Gemeinsamer Ordner-Link kopiert:\n\n"+u)).catch(()=>prompt("Gemeinsamer Ordner-Link:",u))})}
  function addFile(folderId){const root=document.getElementById("modalroot");root.innerHTML=`<div class="modalback"><div class="modal" style="max-width:720px"><div class="modal" style="max-width:720px"><div class="modalhead"><b>Beweismittel hinzufügen</b><button id="x" type="button">×</button></div><form id="fileForm"><label>Name für alle ausgewählten Dateien (optional)<input name="name" placeholder="z. B. Tatortfotos"></label><label>Fotos oder Videos<input name="file" type="file" accept="image/*,video/*" multiple required></label><p class="muted">Mehrfachauswahl ist aktiviert. Dein Handy bzw. Browser öffnet die passende Galerie-, Fotos- oder Dateiauswahl. Alle verfügbaren Bild- und Videoformate werden akzeptiert.</p><div id="st" class="muted">Keine Dateien ausgewählt.</div><div class="actions"><button type="button" class="btn outline" id="c">Abbrechen</button><button type="submit" class="btn dark">Auswahl hochladen</button></div></form></div></div>`;root.querySelector("#x").onclick=root.querySelector("#c").onclick=()=>openPanel(activeCase);const input=root.querySelector('input[type=file]');input.onchange=()=>{const n=input.files?.length||0;root.querySelector("#st").textContent=n?`${n} Datei${n===1?"":"en"} ausgewählt.`:"Keine Dateien ausgewählt."};root.querySelector("#fileForm").onsubmit=e=>uploadMany(e,folderId)}
  async function uploadMany(e,folderId){e.preventDefault();const form=e.currentTarget,files=Array.from(form.elements.file?.files||[]),fallbackName=String(form.elements.name?.value||"").trim(),db=read(),folder=(db.evidence_folders||[]).find(x=>x.id===folderId);if(!client){alert("Supabase ist nicht verfügbar.");return}if(!folder||!files.length){alert("Bitte mindestens eine Datei auswählen.");return}const st=document.getElementById("st"),btn=form.querySelector('button[type="submit"]');btn.disabled=true;folder.items=folder.items||[];let done=0;for(const file of files){st.textContent=`Upload ${done+1} von ${files.length}: ${file.name}`;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`folders/${folderId}/${Date.now()}-${Math.random().toString(36).slice(2,8)}-${safe}`;const result=await client.storage.from(BUCKET).upload(path,file,{contentType:file.type||"application/octet-stream",upsert:false});if(result.error){console.error("Beweis-Upload:",result.error);st.textContent=`Fehler bei ${file.name}: ${result.error.message}`;alert(`Upload fehlgeschlagen:\n${file.name}\n\n${result.error.message}`);continue}const publicUrl=client.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;folder.items.push({id:id(),name:fallbackName||file.name,url:publicUrl,type:file.type||"Datei",file_name:file.name,path,created_at:new Date().toISOString()});done++}write(db);st.textContent=`${done} von ${files.length} Dateien hochgeladen.`;btn.disabled=false;if(done>0)setTimeout(()=>openPanel(activeCase),800)}
  function decorateCase(){document.querySelectorAll("[data-case]").forEach(b=>{if(b.parentElement?.querySelector("[data-case-evidence]"))return;const x=document.createElement("button");x.className="mini";x.dataset.caseEvidence="1";x.textContent="Beweise";x.onclick=e=>{e.stopPropagation();openPanel(b.dataset.case)};b.parentElement.appendChild(x)})}
  const t=setInterval(()=>{if(document.querySelector(".sidebar nav")){addNav();decorateCase()}},500);setTimeout(()=>clearInterval(t),120000);window.DonnerfaustEvidence={open:openPanel};
})();
