/* Rechtsanwalt Donnerfaust – Finanzen, Kasse und Rechnungen */
(() => {
  const DBKEY="donnerfaust_kanzlei_v1";
  const BILLING_RECIPIENT={name:"Thorson Donnerfaust",account:"4693"};
  const REGULAR_PRICES={"Erstberatung / Erstgespräch":1000,"Einfache Rechtsberatung":2500,"Prüfung eines einfachen Falls":3500,"Erstellung eines Schreibens / Antrags":4000,"Außergerichtliche Vertretung":7500,"Umfangreiche außergerichtliche Vertretung":12500,"Vertretung bei Polizei / Vernehmung":7500,"Gerichtliche Vertretung":15000,"Umfangreiches Gerichtsverfahren":20000,"Komplexes Gerichtsverfahren inkl. vollständiger Vorbereitung, Aktenprüfung, Schriftsätzen und Hauptverhandlung":25000};
  const SPECIAL_PRICES={"Dringender / kurzfristiger Auftrag":5000,"Zusätzlicher Termin außerhalb der Kanzlei":2500};
  const read=()=>{try{return JSON.parse(localStorage.getItem(DBKEY)||"{}")}catch{return {}}};
  const write=d=>localStorage.setItem(DBKEY,JSON.stringify(d));
  const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
  const money=n=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(n)||0);
  const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const today=()=>new Date().toISOString().slice(0,10);
  const token=()=>{const a=new Uint8Array(8);crypto.getRandomValues(a);return [...a].map(x=>x.toString(36).padStart(2,"0")).join("").slice(0,12)};
  const base=()=>location.origin+location.pathname.replace(/[^/]*$/,'');
  const ensure=d=>{d.cashbook ||= [];d.invoices ||= [];return d};
  function addStyle(){if(document.getElementById('df-finance-style'))return;const st=document.createElement('style');st.id='df-finance-style';st.textContent='.df-finance-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:18px}.df-fin-card{background:#fff;border:1px solid #dfe3ea;border-radius:16px;padding:18px;box-shadow:0 5px 18px #1111}.df-fin-card small{display:block;color:#667085;text-transform:uppercase;letter-spacing:.08em;font-weight:700;font-size:11px;margin-bottom:7px}.df-fin-card b{font-size:24px}.df-fin-actions{display:flex;gap:10px;flex-wrap:wrap}.df-green{background:#16803c!important;color:#fff!important;border-color:#16803c!important}.df-red{background:#c62828!important;color:#fff!important;border-color:#c62828!important}.df-cash-in{border-left:5px solid #16803c}.df-cash-out{border-left:5px solid #c62828}.df-paid{background:#16803c;color:#fff;border:0;border-radius:999px;padding:6px 10px;font-weight:700}.df-open{background:#fff3cd;color:#7a5a00;border:0;border-radius:999px;padding:6px 10px;font-weight:700;cursor:pointer}.df-invoice-lines{font-size:12px;line-height:1.45;color:#667085}.df-billing-recipient{margin:16px 0;padding:16px 18px;border:1px solid #dfe3ea;border-radius:14px;background:#f8fafc}.df-billing-recipient b{display:block;font-size:15px;margin-top:3px}.df-billing-recipient small{display:block;color:#667085;font-weight:700;text-transform:uppercase;letter-spacing:.06em}@media(max-width:800px){.df-finance-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.df-fin-card b{font-size:19px}}';document.head.appendChild(st)}
  function navButton(id,icon,text){const b=document.createElement('button');b.className='nav';b.dataset.dfFinanceNav=id;b.innerHTML=`<i>${icon}</i>${text}`;return b}
  function injectNav(){const nav=document.querySelector('aside nav');if(!nav)return;addStyle();if(!nav.querySelector('[data-df-finance-nav="finance"]'))nav.appendChild(navButton('finance','▣','Finanzen'));if(!nav.querySelector('[data-df-finance-nav="cash"]'))nav.appendChild(navButton('cash','💶','Kasse'));if(!nav.querySelector('[data-df-finance-nav="billing"]'))nav.appendChild(navButton('billing','🧾','Rechnungen'));if(nav.dataset.dfFinanceBound)return;nav.dataset.dfFinanceBound='1';nav.addEventListener('click',e=>{const f=e.target.closest('[data-df-finance-nav]');if(f){e.preventDefault();e.stopImmediatePropagation();showPage(f.dataset.dfFinanceNav);return}const old=e.target.closest('[data-nav="invoices"]');if(old){e.preventDefault();e.stopImmediatePropagation();showPage('billing')}},true)}
  function pageShell(title,content){const root=document.querySelector('.content');if(!root)return;root.innerHTML=`<div class="intro"><div><div class="eyebrow">KANZLEI / FINANZEN</div><h1>${title}</h1></div></div>${content}`}
  function totals(d){const inv=d.invoices||[];const paid=inv.filter(i=>i.status==='Bezahlt').reduce((s,i)=>s+(Number(i.amount)||0),0);const open=inv.filter(i=>i.status!=='Bezahlt'&&i.status!=='Storniert').reduce((s,i)=>s+(Number(i.amount)||0),0);const income=(d.cashbook||[]).filter(x=>x.kind==='in').reduce((s,x)=>s+(Number(x.amount)||0),0);const expense=(d.cashbook||[]).filter(x=>x.kind==='out').reduce((s,x)=>s+(Number(x.amount)||0),0);return{balance:income-expense,income,expense,paid,open}}
  function finance(){const d=ensure(read()),t=totals(d);pageShell('Finanzübersicht',`<div class="df-finance-stats"><div class="df-fin-card"><small>Kanzleivermögen</small><b>${money(t.balance)}</b></div><div class="df-fin-card"><small>Einnahmen</small><b>${money(t.income)}</b></div><div class="df-fin-card"><small>Ausgaben</small><b>${money(t.expense)}</b></div><div class="df-fin-card"><small>Offene Rechnungen</small><b>${money(t.open)}</b></div></div><div class="panel"><div class="panelhead"><b>Finanzverwaltung</b><div class="df-fin-actions"><button class="btn dark" id="dfGoCash">💶 Kasse öffnen</button><button class="btn outline" id="dfGoBilling">🧾 Rechnungen öffnen</button></div></div><p class="muted">Rechnungen erhöhen das Kanzleivermögen erst, wenn sie als <b>Bezahlt</b> gekennzeichnet wurden. Kassenbewegungen werden mit einem Grund gespeichert.</p></div><div class="grid2"><div class="panel"><div class="panelhead"><b>Letzte Einnahmen</b></div>${d.cashbook.filter(x=>x.kind==='in').slice(-6).reverse().map(cashRow).join('')||'<p class="muted">Noch keine Einnahmen.</p>'}</div><div class="panel"><div class="panelhead"><b>Letzte Ausgaben</b></div>${d.cashbook.filter(x=>x.kind==='out').slice(-6).reverse().map(cashRow).join('')||'<p class="muted">Noch keine Ausgaben.</p>'}</div></div>`);document.getElementById('dfGoCash').onclick=cash;document.getElementById('dfGoBilling').onclick=billing}
  function cashRow(x){return `<div class="listrow ${x.kind==='in'?'df-cash-in':'df-cash-out'}"><b>${x.kind==='in'?'+':'−'} ${money(x.amount)}</b><small>${esc(x.reason)} · ${esc(x.date)}</small></div>`}
  function cash(){const d=ensure(read()),t=totals(d);pageShell('Kassensystem',`<div class="df-finance-stats"><div class="df-fin-card"><small>Kanzleivermögen</small><b>${money(t.balance)}</b></div><div class="df-fin-card"><small>Einzahlungen</small><b>${money(t.income)}</b></div><div class="df-fin-card"><small>Auszahlungen</small><b>${money(t.expense)}</b></div><div class="df-fin-card"><small>Bezahlte Rechnungen</small><b>${money(t.paid)}</b></div></div><div class="panel"><div class="panelhead"><b>Kassenbuch</b><div class="df-fin-actions"><button class="btn df-green" id="dfCashIn">＋ Einzahlung</button><button class="btn df-red" id="dfCashOut">− Auszahlung</button></div></div>${d.cashbook.slice().reverse().map(x=>cashRow(x)+`<button class="mini" data-cash-del="${x.id}">Löschen</button>`).join('')||'<p class="muted">Noch keine Kassenbewegungen.</p>'}</div>`);document.getElementById('dfCashIn').onclick=()=>cashForm('in');document.getElementById('dfCashOut').onclick=()=>cashForm('out');document.querySelectorAll('[data-cash-del]').forEach(b=>b.onclick=()=>{if(confirm('Kassenbuch-Eintrag wirklich löschen?')){const x=ensure(read());x.cashbook=x.cashbook.filter(v=>v.id!==b.dataset.cashDel);write(x);cash()}})}
  function cashForm(kind){const amount=prompt(kind==='in'?'Einzahlung – Betrag (€):':'Auszahlung – Betrag (€):');if(amount===null)return;const n=Number(String(amount).replace(',','.'));if(!Number.isFinite(n)||n<=0)return alert('Bitte einen gültigen positiven Betrag eingeben.');const reason=prompt('Grund:');if(!reason?.trim())return;const d=ensure(read());d.cashbook.push({id:uid(),kind,amount:n,reason:reason.trim(),date:new Date().toLocaleString('de-DE'),source:'manual'});write(d);cash()}
  function serviceSection(title,items){return `<div style="margin-top:16px"><h3 style="margin:0 0 8px">${title}</h3>${Object.entries(items).map(([n,p])=>`<label style="display:flex;align-items:flex-start;gap:10px;margin:8px 0;padding:8px 0"><input type="checkbox" name="service" value="${esc(n)}" data-price="${p}"><span style="flex:1">${esc(n)}</span><strong>${money(p)}</strong></label>`).join('')}</div>`}
  function invoiceForm(){const d=ensure(read());if(!d.clients?.length)return alert('Bitte zuerst einen Mandanten anlegen.');const box=document.createElement('div');box.className='modalback';box.innerHTML=`<div class="modal" style="max-width:800px;max-height:90vh;overflow:auto"><div class="modalhead"><b>Neue Rechnung nach Preisliste</b><button id="fiClose">×</button></div><form id="fiForm"><label>Mandant<select name="client_id" required>${d.clients.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label><label>Akte<select name="case_id"><option value="">Keine Akte</option>${(d.cases||[]).map(c=>`<option value="${esc(c.id)}">${esc(c.file_number)} · ${esc(c.title)}</option>`).join('')}</select></label>${serviceSection('Reguläre Leistungen',REGULAR_PRICES)}${serviceSection('Sonderleistungen',SPECIAL_PRICES)}<div style="margin-top:18px;padding:16px;border:1px solid #ddd;border-radius:12px"><div><small>Grundhonorar</small> <b id="fiRegular">0,00 €</b></div><div><small>Sonderleistungen</small> <b id="fiSpecial">0,00 €</b></div><div style="margin-top:8px;font-size:1.15em"><b>Rechnungswert: <span id="fiTotal">0,00 €</span></b></div></div><div class="actions"><button type="button" class="btn outline" id="fiCancel">Abbrechen</button><button class="btn dark">Rechnung erstellen</button></div></form></div>`;document.body.appendChild(box);const close=()=>box.remove();box.querySelector('#fiClose').onclick=box.querySelector('#fiCancel').onclick=close;const update=()=>{const checked=[...box.querySelectorAll('input[name=service]:checked')];const regular=checked.filter(x=>Object.hasOwn(REGULAR_PRICES,x.value)).reduce((s,x)=>s+Number(x.dataset.price),0);const special=checked.filter(x=>Object.hasOwn(SPECIAL_PRICES,x.value)).reduce((s,x)=>s+Number(x.dataset.price),0);box.querySelector('#fiRegular').textContent=money(regular);box.querySelector('#fiSpecial').textContent=money(special);box.querySelector('#fiTotal').textContent=money(regular+special)};box.querySelectorAll('input[name=service]').forEach(x=>x.onchange=update);box.querySelector('#fiForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const lines=[...box.querySelectorAll('input[name=service]:checked')].map(x=>({name:x.value,price:Number(x.dataset.price),category:Object.hasOwn(SPECIAL_PRICES,x.value)?'Sonderleistung':'Reguläre Leistung'}));if(!lines.length)return alert('Bitte mindestens eine Leistung auswählen.');const inv={id:uid(),invoice_number:'RE-'+new Date().getFullYear()+'-'+String((d.invoices.length||0)+1).padStart(3,'0'),client_id:f.get('client_id'),case_id:f.get('case_id'),lines,amount:lines.reduce((s,x)=>s+x.price,0),date:today(),status:'Offen',paid_at:null,billing_recipient:BILLING_RECIPIENT};d.invoices.push(inv);write(d);close();billing()}}
  async function shareInvoice(id){const d=ensure(read()),i=d.invoices.find(x=>x.id===id);if(!i)return;const cloud=window.DonnerfaustCloud?.supabase;if(!cloud)return alert('Supabase ist noch nicht verfügbar.');const c=d.clients.find(x=>x.id===i.client_id),a=d.cases?.find(x=>x.id===i.case_id);const snapshot={version:2,invoice:{invoice_number:i.invoice_number,date:i.date,status:i.status,amount:i.amount,lines:i.lines||[],billing_recipient:BILLING_RECIPIENT},client:c?{name:c.name,email:c.email,address:c.address}:null,case:a?{file_number:a.file_number,title:a.title}:null};const t=token();const {error}=await cloud.from('shared_invoice_access').insert({token:t,invoice_number:i.invoice_number,snapshot,active:true});if(error){console.error(error);return alert('Freigabelink konnte nicht erstellt werden. Bitte die Supabase-Tabelle shared_invoice_access prüfen.')}const link=`${base()}rechnung/${encodeURIComponent(i.invoice_number)}/${t}`;prompt('Rechnungslink – nur Lesen:',link)}
  function markPaid(id){const d=ensure(read()),i=d.invoices.find(x=>x.id===id);if(!i||i.status==='Bezahlt')return;if(!confirm(`Rechnung ${i.invoice_number} als bezahlt markieren?\n${money(i.amount)} wird dann als Einnahme in die Kasse gebucht.`))return;i.status='Bezahlt';i.paid_at=new Date().toLocaleString('de-DE');d.cashbook.push({id:uid(),kind:'in',amount:Number(i.amount)||0,reason:`Zahlung Rechnung ${i.invoice_number}`,date:new Date().toLocaleString('de-DE'),source:'invoice',invoice_id:i.id});write(d);billing()}
  function billing(){const d=ensure(read()),inv=d.invoices||[];pageShell('Gebühren & Rechnungen',`<div class="intro"><div><p>Rechnungen erstellen, verwalten, bezahlen und schreibgeschützt weitergeben.</p></div><button class="btn dark" id="newFi">+ Rechnung erstellen</button></div><div class="df-billing-recipient"><small>Rechnungsempfänger</small><b>${esc(BILLING_RECIPIENT.name)}</b><span>Konto-Nr.: ${esc(BILLING_RECIPIENT.account)}</span></div><div class="df-finance-stats"><div class="df-fin-card"><small>Rechnungsvolumen</small><b>${money(inv.reduce((s,i)=>s+(Number(i.amount)||0),0))}</b></div><div class="df-fin-card"><small>Bezahlt</small><b>${money(inv.filter(i=>i.status==='Bezahlt').reduce((s,i)=>s+(Number(i.amount)||0),0))}</b></div><div class="df-fin-card"><small>Offen</small><b>${money(inv.filter(i=>i.status!=='Bezahlt').reduce((s,i)=>s+(Number(i.amount)||0),0))}</b></div><div class="df-fin-card"><small>Anzahl</small><b>${inv.length}</b></div></div><div class="panel"><div class="tablewrap"><table><thead><tr><th>RECHNUNG / DATUM</th><th>MANDANT</th><th>AKTE</th><th>LEISTUNGEN</th><th>BETRAG</th><th>STATUS</th><th></th></tr></thead><tbody>${inv.slice().reverse().map(i=>{const c=d.clients.find(x=>x.id===i.client_id),a=d.cases?.find(x=>x.id===i.case_id);return `<tr><td><b>${esc(i.invoice_number)}</b><small>${esc(i.date||'')}</small></td><td>${esc(c?.name||'—')}</td><td>${esc(a?.file_number||'—')}</td><td class="df-invoice-lines">${(i.lines||[]).map(x=>`${esc(x.name)} – ${money(x.price)}`).join('<br>')}</td><td><b>${money(i.amount)}</b></td><td>${i.status==='Bezahlt'?'<button class="df-paid" disabled>✓ Bezahlt</button>':'<button class="df-open" data-paid="'+i.id+'">Als bezahlt markieren</button>'}</td><td><button class="mini" data-inv-share="${i.id}">🔗 Link</button> <button class="mini" data-inv-del="${i.id}">Löschen</button></td></tr>`}).join('')||'<tr><td colspan="7">Keine Rechnungen vorhanden.</td></tr>'}</tbody></table></div></div>`);document.getElementById('newFi').onclick=invoiceForm;document.querySelectorAll('[data-paid]').forEach(b=>b.onclick=()=>markPaid(b.dataset.paid));document.querySelectorAll('[data-inv-del]').forEach(b=>b.onclick=()=>{if(confirm('Rechnung wirklich endgültig löschen?')){const x=ensure(read());x.invoices=x.invoices.filter(v=>v.id!==b.dataset.invDel);write(x);billing()}});document.querySelectorAll('[data-inv-share]').forEach(b=>b.onclick=()=>shareInvoice(b.dataset.invShare))}
  function showPage(which){injectNav();if(which==='finance')finance();else if(which==='cash')cash();else billing()}
  function watch(){injectNav();const root=document.getElementById('app');if(!root)return;new MutationObserver(()=>injectNav()).observe(root,{childList:true,subtree:true})}
  watch();
})();